language: common-lisp

env:
  matrix:
    - LISP=allegro
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=ecl
    - LISP=abcl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - cl -e '(in-package :cl-user)'
       -e "(ql:quickload '(prove let-over-lambda))"
       -e '(setf prove:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(or (prove:run :let-over-lambda-test)
               (uiop:quit -1))'
